<?php

declare(strict_types=1);

function getFeaturedCars(): array
{
    return [
        'aqua-hybrid-2020' => [
            'id' => 'aqua-hybrid-2020',
            'name' => 'Toyota Aqua Hybrid',
            'make' => 'Toyota',
            'model' => 'Aqua',
            'year' => '2020',
            'mileage' => '58,000 km',
            'engine' => '1.5L Hybrid',
            'transmission' => 'Automatic',
            'fuel' => 'Hybrid Petrol',
            'grade' => '4.5',
            'vin' => 'NHP10-2948756',
            'price' => 'KES 1,980,000',
            'color' => 'Pearl White',
            'instagram' => 'https://www.instagram.com/p/DWhaTF7CXO-/',
            'image' => 'https://www.instagram.com/p/DWhaTF7CXO-/media/?size=l',
        ],
        'harrier-elegance-2019' => [
            'id' => 'harrier-elegance-2019',
            'name' => 'Toyota Harrier Elegance',
            'make' => 'Toyota',
            'model' => 'Harrier',
            'year' => '2019',
            'mileage' => '64,000 km',
            'engine' => '2.0L Petrol',
            'transmission' => 'CVT',
            'fuel' => 'Petrol',
            'grade' => '4.0',
            'vin' => 'ZSU60-1129034',
            'price' => 'KES 4,350,000',
            'color' => 'Jet Black',
            'instagram' => 'https://www.instagram.com/p/DWWagZxDGp0/',
            'image' => 'https://www.instagram.com/p/DWWagZxDGp0/media/?size=l',
        ],
        'cx5-awd-2018' => [
            'id' => 'cx5-awd-2018',
            'name' => 'Mazda CX-5 AWD',
            'make' => 'Mazda',
            'model' => 'CX-5',
            'year' => '2018',
            'mileage' => '71,000 km',
            'engine' => '2.2L Diesel',
            'transmission' => 'Automatic',
            'fuel' => 'Diesel',
            'grade' => '4.0',
            'vin' => 'KF2P-3051821',
            'price' => 'KES 3,780,000',
            'color' => 'Deep Crystal Blue',
            'instagram' => 'https://www.instagram.com/p/DWRGmEXkuSO/',
            'image' => 'https://www.instagram.com/p/DWRGmEXkuSO/media/?size=l',
        ],
        'vezel-hybrid-2019' => [
            'id' => 'vezel-hybrid-2019',
            'name' => 'Honda Vezel Hybrid',
            'make' => 'Honda',
            'model' => 'Vezel',
            'year' => '2019',
            'mileage' => '53,000 km',
            'engine' => '1.5L Hybrid',
            'transmission' => 'Automatic',
            'fuel' => 'Hybrid Petrol',
            'grade' => '4.5',
            'vin' => 'RU3-2476130',
            'price' => 'KES 3,150,000',
            'color' => 'Urban Titanium',
            'instagram' => 'https://www.instagram.com/p/DWgCxKNDNud/',
            'image' => 'https://www.instagram.com/p/DWgCxKNDNud/media/?size=l',
        ],
        'xtrail-7seater-2018' => [
            'id' => 'xtrail-7seater-2018',
            'name' => 'Nissan X-Trail 7-Seater',
            'make' => 'Nissan',
            'model' => 'X-Trail',
            'year' => '2018',
            'mileage' => '79,000 km',
            'engine' => '2.0L Petrol',
            'transmission' => 'CVT',
            'fuel' => 'Petrol',
            'grade' => '4.0',
            'vin' => 'NT32-1834092',
            'price' => 'KES 2,980,000',
            'color' => 'Silver Metallic',
            'instagram' => 'https://www.instagram.com/p/DWB0JDzEwcP/',
            'image' => 'https://www.instagram.com/p/DWB0JDzEwcP/media/?size=l',
        ],
        'forester-xt-2017' => [
            'id' => 'forester-xt-2017',
            'name' => 'Subaru Forester XT',
            'make' => 'Subaru',
            'model' => 'Forester',
            'year' => '2017',
            'mileage' => '83,000 km',
            'engine' => '2.0L Turbo',
            'transmission' => 'Automatic',
            'fuel' => 'Petrol',
            'grade' => '4.0',
            'vin' => 'SJG-0918405',
            'price' => 'KES 2,740,000',
            'color' => 'Ice Silver',
            'instagram' => 'https://www.instagram.com/p/DV-fRYUCtbj/',
            'image' => 'https://www.instagram.com/p/DV-fRYUCtbj/media/?size=l',
        ],
        'rav4-gx-2019' => [
            'id' => 'rav4-gx-2019',
            'name' => 'Toyota RAV4 GX',
            'make' => 'Toyota',
            'model' => 'RAV4',
            'year' => '2019',
            'mileage' => '62,000 km',
            'engine' => '2.0L Petrol',
            'transmission' => 'CVT',
            'fuel' => 'Petrol',
            'grade' => '4.5',
            'vin' => 'MXAA54-1049371',
            'price' => 'KES 4,180,000',
            'color' => 'White Pearl',
            'instagram' => 'https://www.instagram.com/p/DVxjq5pjnyv/',
            'image' => 'https://www.instagram.com/p/DVxjq5pjnyv/media/?size=l',
        ],
        'demio-skyactive-2018' => [
            'id' => 'demio-skyactive-2018',
            'name' => 'Mazda Demio Skyactiv',
            'make' => 'Mazda',
            'model' => 'Demio',
            'year' => '2018',
            'mileage' => '49,000 km',
            'engine' => '1.3L Petrol',
            'transmission' => 'Automatic',
            'fuel' => 'Petrol',
            'grade' => '4.5',
            'vin' => 'DJ3FS-6401282',
            'price' => 'KES 1,620,000',
            'color' => 'Machine Grey',
            'instagram' => 'https://www.instagram.com/p/DVibsowDItL/',
            'image' => 'https://www.instagram.com/p/DVibsowDItL/media/?size=l',
        ],
        'crown-athlete-2017' => [
            'id' => 'crown-athlete-2017',
            'name' => 'Toyota Crown Athlete',
            'make' => 'Toyota',
            'model' => 'Crown Athlete',
            'year' => '2017',
            'mileage' => '66,000 km',
            'engine' => '2.5L Hybrid',
            'transmission' => 'Automatic',
            'fuel' => 'Hybrid Petrol',
            'grade' => '4.0',
            'vin' => 'AWS210-5028714',
            'price' => 'KES 4,950,000',
            'color' => 'Royal Black',
            'instagram' => 'https://www.instagram.com/p/DVTQIuiEU5u/',
            'image' => 'https://www.instagram.com/p/DVTQIuiEU5u/media/?size=l',
        ],
        'landcruiser-prado-2016' => [
            'id' => 'landcruiser-prado-2016',
            'name' => 'Toyota Land Cruiser Prado',
            'make' => 'Toyota',
            'model' => 'Prado',
            'year' => '2016',
            'mileage' => '89,000 km',
            'engine' => '2.8L Diesel',
            'transmission' => 'Automatic',
            'fuel' => 'Diesel',
            'grade' => '4.0',
            'vin' => 'GDJ150-0217458',
            'price' => 'KES 6,950,000',
            'color' => 'Champagne Gold',
            'instagram' => 'https://www.instagram.com/p/DWBK8jzj3wU/',
            'image' => 'https://www.instagram.com/p/DWBK8jzj3wU/media/?size=l',
        ],
        'fit-rs-2020' => [
            'id' => 'fit-rs-2020',
            'name' => 'Honda Fit RS',
            'make' => 'Honda',
            'model' => 'Fit RS',
            'year' => '2020',
            'mileage' => '37,000 km',
            'engine' => '1.5L Petrol',
            'transmission' => 'Automatic',
            'fuel' => 'Petrol',
            'grade' => '4.5',
            'vin' => 'GK5-4512208',
            'price' => 'KES 2,050,000',
            'color' => 'Sunset Orange',
            'instagram' => 'https://www.instagram.com/p/DWA-rnMjMgn/',
            'image' => 'https://www.instagram.com/p/DWA-rnMjMgn/media/?size=l',
        ],
        'corolla-fielder-2019' => [
            'id' => 'corolla-fielder-2019',
            'name' => 'Toyota Corolla Fielder',
            'make' => 'Toyota',
            'model' => 'Corolla Fielder',
            'year' => '2019',
            'mileage' => '55,000 km',
            'engine' => '1.5L Petrol',
            'transmission' => 'Automatic',
            'fuel' => 'Petrol',
            'grade' => '4.5',
            'vin' => 'NZE161-9187203',
            'price' => 'KES 2,420,000',
            'color' => 'White',
            'instagram' => 'https://www.instagram.com/p/DWOQscdjeWO/',
            'image' => 'https://www.instagram.com/p/DWOQscdjeWO/media/?size=l',
        ],
        'featured-dwdxsfkdoqh' => [
            'id' => 'featured-dwdxsfkdoqh',
            'name' => 'Featured Vehicle',
            'make' => 'Unknown',
            'model' => 'Unknown',
            'year' => 'N/A',
            'mileage' => 'N/A',
            'engine' => 'N/A',
            'transmission' => 'N/A',
            'fuel' => 'N/A',
            'grade' => 'N/A',
            'vin' => 'N/A',
            'price' => 'On Request',
            'color' => 'N/A',
            'instagram' => 'https://www.instagram.com/p/DWDxsfKDOqH/',
            'image' => 'https://www.instagram.com/p/DWDxsfKDOqH/media/?size=l',
        ],
        'featured-dwbyrnpjyrz' => [
            'id' => 'featured-dwbyrnpjyrz',
            'name' => 'Featured Vehicle',
            'make' => 'Unknown',
            'model' => 'Unknown',
            'year' => 'N/A',
            'mileage' => 'N/A',
            'engine' => 'N/A',
            'transmission' => 'N/A',
            'fuel' => 'N/A',
            'grade' => 'N/A',
            'vin' => 'N/A',
            'price' => 'On Request',
            'color' => 'N/A',
            'instagram' => 'https://www.instagram.com/p/DWBYrnpjYrZ/',
            'image' => 'https://www.instagram.com/p/DWBYrnpjYrZ/media/?size=l',
        ],
        'featured-dvvm4eyjv7g' => [
            'id' => 'featured-dvvm4eyjv7g',
            'name' => 'Featured Vehicle',
            'make' => 'Unknown',
            'model' => 'Unknown',
            'year' => 'N/A',
            'mileage' => 'N/A',
            'engine' => 'N/A',
            'transmission' => 'N/A',
            'fuel' => 'N/A',
            'grade' => 'N/A',
            'vin' => 'N/A',
            'price' => 'On Request',
            'color' => 'N/A',
            'instagram' => 'https://www.instagram.com/p/DVvM4eYjv7G/',
            'image' => 'https://www.instagram.com/p/DVvM4eYjv7G/media/?size=l',
        ],
    ];
}

function getShuffledFeaturedCars(): array
{
    $cars = getFeaturedCars();
    $keys = array_keys($cars);
    shuffle($keys);

    $shuffled = [];
    foreach ($keys as $key) {
        $shuffled[$key] = $cars[$key];
    }

    return $shuffled;
}
